# Generated by Django 4.2.8 on 2023-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept_nm', models.CharField(max_length=10)),
                ('dept_res_id', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_num', models.BigIntegerField(blank=True, null=True)),
                ('dept_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_mail', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctor_nm', models.CharField(max_length=10)),
                ('doctor_tel', models.CharField(max_length=20)),
                ('doctor_gender', models.CharField(max_length=10)),
                ('doctor_med_field', models.CharField(max_length=40)),
                ('doctor_salary', models.IntegerField()),
                ('doctor_pw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nok',
            fields=[
                ('protector_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('protector_nm', models.CharField(max_length=10)),
                ('protector_tel', models.CharField(max_length=20)),
                ('protector_gender', models.CharField(max_length=10)),
                ('protector_birth_day', models.CharField(max_length=8)),
                ('protector_pw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nurse_salery', models.IntegerField()),
                ('nurse_name', models.CharField(max_length=10)),
                ('nurse_tel', models.CharField(max_length=20)),
                ('nurse_gender', models.CharField(max_length=10)),
                ('nurse_med_field', models.CharField(max_length=40)),
                ('nurse_m_work', models.CharField(max_length=40)),
                ('nurse_pw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=10)),
                ('patient_birthday', models.CharField(max_length=8)),
                ('patient_tel', models.CharField(max_length=20)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_home', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_accept_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_hos', models.IntegerField()),
                ('patient_pw', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
